"""Canonical contract field dictionaries for schema and acceptance checks."""

from __future__ import annotations

MARKET_DAILY_COLUMNS: tuple[str, ...] = (
    "symbol",
    "trade_date",
    "open",
    "high",
    "low",
    "close",
    "volume",
    "amount",
    "adj_factor",
    "source",
    "version",
)

MARKET_EVENT_COLUMNS: tuple[str, ...] = (
    "event_id",
    "event_type",
    "symbol",
    "event_date",
    "asof_date",
    "actor",
    "value",
    "payload_json",
    "source",
    "version",
)

TABLE_COLUMNS: dict[str, tuple[str, ...]] = {
    "data_source": (
        "source_id",
        "name",
        "purpose",
        "auth_status",
        "quota",
        "cost",
        "owner",
        "priority",
        "health_status",
        "created_at",
        "updated_at",
    ),
    "instrument_master": (
        "symbol",
        "name",
        "instrument_type",
        "exchange",
        "board",
        "list_date",
        "delist_date",
        "status",
        "is_st",
        "created_at",
        "updated_at",
    ),
    "trade_calendar": (
        "trade_date",
        "market",
        "is_open",
        "open_time",
        "close_time",
        "prev_trade_date",
        "next_trade_date",
    ),
    "limit_suspension": (
        "symbol",
        "trade_date",
        "limit_up",
        "limit_down",
        "is_suspended",
        "reason",
    ),
    "factor_signal": (
        "trade_date",
        "symbol",
        "factor_name",
        "value",
        "model_version",
        "source_run_id",
        "params_hash",
    ),
    "quality_issue": (
        "issue_id",
        "dataset",
        "symbol",
        "trade_date",
        "check_type",
        "severity",
        "status",
        "source_a",
        "source_b",
        "diff",
        "created_at",
        "updated_at",
    ),
    "strategy_version": (
        "strategy_id",
        "version",
        "status",
        "parameter_set_id",
        "code_version",
        "risk_config",
        "effective_date",
        "created_at",
    ),
    "target_position": (
        "target_id",
        "trade_date",
        "strategy_id",
        "strategy_version",
        "symbol",
        "target_weight",
        "target_amount",
        "target_volume",
        "reason",
        "data_version",
        "created_at",
    ),
    "standard_order": (
        "order_id",
        "idem_key",
        "trade_date",
        "strategy_id",
        "symbol",
        "side",
        "quantity",
        "price_type",
        "limit_price",
        "valid_date",
        "risk_tags",
        "status",
        "created_at",
        "updated_at",
    ),
    "execution_fill": (
        "fill_id",
        "order_id",
        "broker_order_id",
        "symbol",
        "side",
        "filled_qty",
        "filled_price",
        "fee",
        "status",
        "trade_time",
        "created_at",
    ),
    "account_snapshot": (
        "account_id",
        "trade_date",
        "cash",
        "market_value",
        "total_asset",
        "position_detail",
        "reconcile_diff",
        "created_at",
    ),
    "task_run": (
        "run_id",
        "task_name",
        "status",
        "started_at",
        "finished_at",
        "message",
        "created_at",
    ),
    "alert": (
        "alert_id",
        "level",
        "category",
        "status",
        "title",
        "detail",
        "created_at",
        "updated_at",
    ),
    "operation_audit": (
        "audit_id",
        "actor",
        "action",
        "target_type",
        "target_id",
        "reason",
        "before_state",
        "after_state",
        "created_at",
    ),
    "data_sync_run": (
        "run_id",
        "trigger",
        "status",
        "source",
        "start_date",
        "end_date",
        "max_trade_date_before",
        "max_trade_date_after",
        "normalized_rows",
        "quality_ok",
        "trade_allowed",
        "issue_count",
        "fail_reason",
        "detail",
        "inflight",
        "progress_pct",
        "progress_done",
        "progress_total",
        "progress_symbol",
        "started_at",
        "finished_at",
        "created_at",
    ),
    "data_sync_lock": (
        "lock_id",
        "run_id",
        "holder",
        "acquired_at",
        "expires_at",
    ),
    "market_data_file": (
        "dataset",
        "file_path",
        "row_count",
        "min_trade_date",
        "max_trade_date",
        "data_version",
        "created_at",
    ),
    "research_run": (
        "run_id",
        "strategy_id",
        "status",
        "inflight",
        "progress_pct",
        "progress_done",
        "progress_total",
        "progress_label",
        "fail_reason",
        "detail",
        "started_at",
        "finished_at",
        "created_at",
    ),
    "factor_run": (
        "run_id",
        "strategy_id",
        "status",
        "inflight",
        "progress_pct",
        "progress_done",
        "progress_total",
        "progress_label",
        "fail_reason",
        "detail",
        "started_at",
        "finished_at",
        "created_at",
    ),
    "event_pull_run": (
        "run_id",
        "status",
        "inflight",
        "progress_pct",
        "progress_done",
        "progress_total",
        "progress_label",
        "fail_reason",
        "detail",
        "started_at",
        "finished_at",
        "created_at",
    ),
    "symbol_tag": (
        "tag",
        "symbol",
        "source",
        "note",
        "updated_at",
    ),
    "paper_override": (
        "strategy_id",
        "symbol",
        "action",
        "weight",
        "reason",
        "actor",
        "updated_at",
    ),
    "market_event": (
        "event_id",
        "event_type",
        "symbol",
        "event_date",
        "asof_date",
        "actor",
        "value",
        "payload_json",
        "source",
        "version",
    ),
}

REQUIRED_TABLES: tuple[str, ...] = tuple(TABLE_COLUMNS.keys())
